### ISSUE TITLE
Java Platform SE停止工作

### ISSUE THREAD

**Issue by ldliuzhen** [CikeyQi/unidbg-fetch-qsign-gui#3]
运行一段时间后Java会停止工作，似乎是因为内存设置太小的原因。

在批处理文件里，把set DEFAULT_JVM_OPTS=-Xmx2048m加上后，不再出现停止工作的情况。

**Comment by CikeyQi** [comment]
JVM默认分配内存是物理内存的1/4，我们并没有去设置内存大小
